version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=easypass_db
      - DB_USERNAME=easypass_user
      - DB_PASSWORD=easypass_password
    depends_on:
      - db
    volumes:
      - storage_data:/var/www/html/storage
    networks:
      - easypass_network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=easypass_db
      - MYSQL_USER=easypass_user
      - MYSQL_PASSWORD=easypass_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - easypass_network

volumes:
  mysql_data:
  storage_data:

networks:
  easypass_network:
    driver: bridge
