[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction"
]

[phases.build]
cmds = [
    "php artisan config:clear || echo 'Config clear failed'",
    "php artisan cache:clear || echo 'Cache clear failed'"
]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
