# Railway configuration for Laravel project
[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
APP_ENV = "production"
APP_DEBUG = "false"
APP_KEY = { generate = true }
DB_CONNECTION = "pgsql"
QUEUE_CONNECTION = "database"
SESSION_DRIVER = "database"
CACHE_DRIVER = "database"
