services:
  # Backend Service (Laravel API)
  - type: web
    name: easypass-backend
    env: php
    region: oregon
    plan: free
    buildCommand: cd backend && composer install --no-dev --optimize-autoloader
    startCommand: cd backend && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT
    healthCheckPath: /api/health
    envVars:
      - key: APP_NAME
        value: EasyPass
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: mysql
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: CORS_ALLOWED_ORIGINS
        value: https://easypass-frontend.onrender.com

  # Frontend Service (Vue.js)
  - type: web
    name: easypass-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://easypass-backend.onrender.com
      - key: VITE_APP_NAME
        value: EasyPass EMS
      - key: VITE_APP_VERSION
        value: 1.0.0
